name: trackizer_ui
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8

  flutter_svg: ^2.2.0
  flutter_screenutil: ^5.9.3
  syncfusion_flutter_gauges: ^30.1.40
  dotted_border: ^3.1.0
  dotted_line: ^3.2.3
  curved_navigation_bar: ^1.0.6
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

flutter:
  # assets:
  #   - assets/images/logo.svg

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/logo.svg
    - assets/images/welcomeScreen_images/welcomeIcons.svg
    - assets/images/welcomeScreen_images/right_bubble.svg
    - assets/images/welcomeScreen_images/left_bubble.png
    - assets/images/welcomeScreen_images/blury.png
    - assets/images/credit_card_screen_images/MasterCardLogo.svg
    - assets/images/credit_card_screen_images/Vector.svg
    - assets/images/credit_card_screen_images/add.svg
    - assets/images/subscription_info_images/Ellipse.svg
    - assets/icons/Settings.svg
    - assets/icons/spotify.svg
    - assets/icons/youtube.svg
    - assets/icons/cloud.svg
    - assets/icons/netflix.svg
    - assets/icons/header_icons/ArrowDown.svg
    - assets/icons/header_icons/Trash.svg
    - assets/images/Spotify Logo.png
    - assets/images/YT Premium Lgoo.png
    - assets/images/OneDrive Logo.png
